"""Added email column to user

Revision ID: 37c0be3f9fbb
Revises: 
Create Date: 2025-04-22 13:31:36.137628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37c0be3f9fbb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        # Adding the 'email' column to the 'user' table
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        
        # Creating the unique constraint on the 'email' column
        batch_op.create_unique_constraint('uq_user_email', ['email'])  # Corrected this line

    # ### end Alembic commands ###




def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
